-- Datos de demostración de TU SUPERMARKET.
--
-- La siembra no vive en este archivo sino en la función `reset_demo()` de la
-- base de datos; aquí solo se la invoca. Si el SQL estuviera duplicado, las dos
-- copias acabarían divergiendo.
--
-- La función solo es ejecutable por los roles administrativos: borra productos,
-- categorías, pedidos e inventario sin filtro, así que no se concede a los
-- usuarios de la aplicación. Se ejecuta desde el editor SQL de Supabase.
--
-- Deja el sistema así:
--   · 6 categorías y 15 subcategorías
--   · 24 productos con precios en COP, imágenes de `public/demo/`, códigos de
--     barras, tres en oferta, uno agotado y dos próximos a vencer
--   · 3 pedidos de muestra, uno en cada estado:
--       #1 Carlos Ramírez  · entregado, pagado en efectivo hace unas horas
--       #2 Ana Torres      · cancelado
--       #3 María Gómez     · pendiente, listo para alistar y entregar
--
-- Las fechas son relativas al momento de ejecutarla, así que el cierre de caja
-- del día siempre tiene una venta que mostrar.
--
-- Ejecutar desde el editor SQL de Supabase:

select public.reset_demo();

-- Para dejar el catálogo completamente en blanco, sin datos de ejemplo:
--
--   delete from public.orders;
--   delete from public.stock_entries;
--   delete from public.products;
--   delete from public.categories;
